### PR TITLE
purge: deprecate the unstable WinEvent Logging component

### PR DESCRIPTION
**Pull request by smusali**
We have decided to remove and deprecate the unstable WinEvent Logging component and already announced it to the customers by saying it is going to be gone in the next upcoming major release.

Ref: LOG-7194
Semver: patch

### CODE REVIEW

**Review by darinspivey — APPROVED** [review]
Looks good!

**Comment by dm36** [comment]
@smusali would update the commit body and commit message to read something like:

Remove and deprecate the unstable WinEvent Logging component.

**Review by dm36 — COMMENTED** [review]
@smusali would update the commit body and commit message to read something like:

Remove and deprecate the unstable WinEvent Logging component.

otherwise: lgtm!

**Comment by smusali** [comment]
updated, @dm36! Can you re-approve, @darinspivey?

**Review by dm36 — APPROVED** [review]

**Review by darinspivey — APPROVED** [review]

**Pull request merged**
