### PR TITLE
Use systemd service name as the app name

### PR DESCRIPTION
**Pull request by summatix**
https://github.com/logdna/logdna-agent/issues/168

### CODE REVIEW

**Comment by summatix** [comment]
I've built this and have it deployed. Logs are showing the correct name now in my LogDNA views.

**Comment by jimaek** [comment]
Are there any problems with this PR? I would love to see it merged.

**Review by smusali — APPROVED** [review]

**Comment by jimaek** [comment]
I believe it will fix the issue below right?
docker

Currently all logs are show syslog as the reporting app which makes them very hard to read.

**Comment by c-nixon** [comment]
This looks good to me and I think it's the correct behaviour, my only question is whether it could break any existing code out there that relies on the current behaviour. I think this might be a major semver change in that case?

@darinspivey @smusali Does the next release have any backcompat guarantees that would mean we need to make this opt in?

**Comment by darinspivey** [comment]
> my only question is whether it could break any existing code out there that relies on the current behaviour.

Agreed.  I have a few concerns with merging this change:

1. We have to stop doing (and contributing) to these long conditionals.  They're hard to test, and impossible to change safely (as we're seeing from the difficulty presented here).

2. Although this change works for this particular use case, we don't know who out there might break from it.  There could be people who have already navigated this conditional to make values what they need.

3.  There is no way to make this "backwards compatible" code without adding an opt-in as @c-nixon suggested, and we're trying to archive this project, not add new features.

We need to loop in some more people such as product to make this decision, but my vote is to not take the risk, close it, and move forward fixing this in places where we will have more release control (such as the brand new repos/releases in the works)

**Review by darinspivey — APPROVED** [review]
Approving this change since the public has requested it.  It hopefully won't "break" anyone, but we can solve that problem if/when it arises.  At worst, it'll just munge the expected `app` value which isn't terrible.

**Comment by smusali** [comment]
@summatix, this `Pull Request` has some merge conflicts; can you rebase this on top of `master`? Thanks!

**Comment by smusali** [comment]
Been done by #210 - thanks!

**Pull request closed without merging**
